config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end

  resources :users, only: [:show] do
    collection do
      get 'privacy', to: 'users/privacy'
      get 'exhibit', to: 'users/exhibit'
    end
    get :favorites, on: :collection
  end

  root to:'items#index'
  resources :addresses, only: [:new]

  resources :items do
    collection do
      match 'search', to: 'items#search', via: [:get, :post]
      get 'price_range', defaults: { format: 'json' }
      get 'category_children', defaults: { format: 'json' }
      get 'category_grandchildren', defaults: { format: 'json' }
    end

    resources :purchase do
      collection do
        get 'index', to: 'purchase#index'
        post 'pay', to: 'purchase#pay'
        get 'done', to: 'purchase#done'
      end
    end

    resources :comments, only: [:create, :show, :edit, :destroy]
    collection do
      get 'search'
    end

    resource :favorites, only: [:create, :destroy]
  end

  resources :cards, only: [:new, :show] do
    collection do
      post 'show', to: 'cards#show'
      post 'pay', to: 'cards#pay'
      post 'delete', to: 'cards#delete'
      get 'new', to: 'cards#new'
    end
  end

  resources :categories, only: [:index]

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:facebook, :google_oauth2], password_length: 7..128

  has_one :address
  has_one :card
  has_many :sns_credentials
  has_many :items

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :birth_year
  validates :birth_year_id, numericality: { other_than: 0 }

  belongs_to_active_hash :birth_month
  validates :birth_month_id, numericality: { other_than: 0 }

  belongs_to_active_hash :birth_day
  validates :birth_day_id, numericality: { other_than: 0 }

  has_one :address
  has_one :card
  has_many :items
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :nickname, :birth_day, :first_name, :last_name, :first_name_kana, :last_name_kana, :encrypted_password, :email, presence: true

  validates :first_name, :last_name,
  format: {with: /\A[ぁ-んァ-ン一-龥]/, message: 'を全角で入力してください' }

  validates :first_name_kana, :last_name_kana,
  format: { with: /\A([ァ-ン]|ー)+\z/, message: 'を全角カタカナで入力してください' }

  validates :email,
  format: { with: /\A[\x21-\x3f\x41-\x7e]+@(?:[-a-z0-9]+\.)+[a-z]{2,}\z/i, message: 'を正しいフォーマットで入力してください'}

  validates :password,
  format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]{7,128}/, message: 'を正しいフォーマットで入力してください'}

  def self.from_omniauth(auth)
    sns = SnsCredential.where(provider: auth.provider, uid: auth.uid).first_or_create
    # sns認証したことがあればアソシエーションで取得
    # 無ければemailでユーザー検索して取得orビルド(保存はしない)
    user = sns.user || User.where(email: auth.info.email).first_or_initialize(
      nickname: auth.info.name,
        email: auth.info.email
    )
    # userが登録済みの場合はそのままログインの処理へ行くので、ここでsnsのuser_idを更新しておく
    if user.persisted?
      sns.user = user
      sns.save
    end
    { user: user, sns: sns }
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  def facebook
    authorization
  end

  def google_oauth2
    authorization
  end

  def failure
    redirect_to root_path
  end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end

  private

  def authorization
    sns_info = User.from_omniauth(request.env["omniauth.auth"])
    @user = sns_info[:user]

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
    else
      @sns_id = sns_info[:sns].id
      render template: 'devise/registrations/new'
    end
  end

end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    @user = User.new
  end

  # POST /resource
  def create

    if params[:sns_auth] == 'true'
      pass = Devise.friendly_token
      params[:user][:password] = pass
      params[:user][:password_confirmation] = pass
    end
    # super

    @user = User.new(sign_up_params) #登録1ページ目から送られてきたパラメータを@userに代入
    unless @user.valid? #validメソッドを使ってバリデーションチェック
      flash.now[:alert] = @user.errors.full_messages
      render :new and return #and returnを使って条件分岐を明示的に終了させている。
    end
    session["devise.regist_data"] = {user: @user.attributes}
     #sessionにハッシュオブジェクトで情報保持させるため、attributesメソッドでデータ整形。

    session["devise.regist_data"][:user]["password"] = params[:user][:password]
    #前述で含まれなかった情報を代入。

    #ネットでは、sessionに関して、ネスト構造になっている場合は、2階層目以降を文字列表記にする必要があるとの噂がありましたが、両方ともシンボル型でOKとのこと。
    #要は、前述のコードがシンボル型ならこの箇所もシンボル型に、文字列ならこの箇所も文字列に、合わせる必要がある。

    #params[:user][:password]において、paramsの中身（userモデルのpasswordカラム）から値を取り出している。ネスト構造な書き方。
    # （params[:password]ではなく、params[:user][:password]という書き方で、モデル・カラムという順番で指定している）
    #その値をsession["devise.regist_data”]の中の[:user]というハッシュの[“password”]というキーのバリューに代入している。
    @address = @user.build_address
    #build_addressメソッドはhas_one :addressのアソシエーションを設定すると使用可。関連づけのあるnewメソッドのようなもの。
    render :new_address
  end

  def create_address
    @user = User.new(session["devise.regist_data"]["user"])
    #session["devise.regist_data”]の中の["user”]というハッシュの情報を@userに代入している。

    #user、という同じハッシュがアクションをまたぐ（create~create_address）と、create_addressアクションにおいては自動的に文字列になってしまう。
    #binding.pryで検証すると確認できるとのこと。
    #そのため文字列表記で指定しないといけない。

    @address = Address.new(address_params)
    unless @address.valid?
      flash.now[:alert] = @address.errors.full_messages
      render :new_address and return
    end
    @user.build_address(@address.attributes) #送られてきたparamsをbuild_addressを用いて@userに代入
    @user.save
    session["devise.regist_data"]["user"].clear #sessionを明示的に削除 セキュリティ上必要
    sign_in(:user, @user) #登録後ログイン状態になるようにしている
    redirect_to root_path
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :first_name, :last_name, :first_name_kana, :last_name_kana, :birth_year_id, :birth_month_id, :birth_day_id])
  end

  def address_params
    params.require(:address).permit(:first_name, :last_name, :first_name_kana, :last_name_kana, :zip_code, :prefecture_id, :city, :block_number, :apartment_name, :user, :phone_number)
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show]

  def show
    @user = User.find(params[:id])
    @items = @user.items

    favorites = Favorite.where(user_id: current_user.id).pluck(:item_id)
    @favorite_list = Item.find(favorites)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/exhibit.html.haml
= render "shared/header-sub"
.mypage-wrap
  .mypage-wrap-contents
    .left-contents
      .lists-head
        .list-inner
          .list-inner__title
            = link_to "マイページ",user_path(current_user.id)
          .list-inner__title
            = link_to "出品する",new_item_path
          .list-inner__title
            = link_to "出品した商品 出品中",exhibit_users_path
          .list-inner__title
            = link_to "出品した商品 売却済み"
          .list-inner__title
            = link_to "購入した商品 過去の取引"
      .setting
        .setting__title 設定
      .lists-foot
        .list
          .list-inner__title
            - if current_user.card
              = link_to "クレジットカード詳細", card_path(current_user)
            - else
              = link_to "クレジットカード登録", new_card_path
        .list
          .list-inner__title
            - if user_signed_in?
              = link_to "ログアウト", destroy_user_session_path, method: :delete
            - else
              = link_to "ログイン", new_user_session_path, method: :get

    .main-contents
      .Pickup-category__product__lists
      - @items.each do |item|
        = link_to item_path(item.id) do
          - if item.trading_status_id == 1 && item.user_id == current_user.id
            .Pickup-category__product__lists__list
              .Pickup-category__product__lists__list__picture
                = image_tag item.images.first.image.url, size:'220*150'
              .Pickup-category__product__lists__list__body
                .Pickup-category__product__lists__list__body__name
                  = item.name
                .Pickup-category__product__lists__list__body__details
                  %ul
                    %li= "#{item.price}円"
                    %li
                      =icon('fa','star')
                      4
                  %p（税込）

= render "shared/footer-sub"

app/views/users/index.html.haml
- if user_signed_in?
  = link_to "ログアウト", destroy_user_session_path, method: :delete
- else
  = link_to "ログイン", new_user_session_path, method: :get

app/views/users/logout.html.haml
= render "shared/header-sub"

.user-finish-wrap
  .finish-form
    .finishWrap
      .user-infoWrap
        .user-finish__info
          ログアウトしました。

      = form_with model: @users, local: true do |f|
        .user-login__button
          = f.submit "ログインする", class: "submit"
        .card-info
          *購入の際にはログインが必要となります。
        .user-mypage__button
          = f.submit "トップページへ戻る", class: "submit"

= render "shared/footer-sub"

app/views/users/privacy.html.haml
%h1 このウェブサイトは、テックキャンプ最終課題の実装を紹介するサイトです。
%br
%h2 個人情報保護方針
%h3 当社は、以下のとおり個人情報保護方針を定め、個人情報保護の仕組みを構築し、全従業員に個人情報保護の重要性の認識と取組みを徹底させることにより、個人情報の保護を推進致します。
%br
%h2 個人情報の管理
%h3 当社は、お客さまの個人情報を正確かつ最新の状態に保ち、個人情報への不正アクセス・紛失・破損・改ざん・漏洩などを防止するため、セキュリティシステムの維持・管理体制の整備・社員教育の徹底等の必要な措置を講じ、安全対策を実施し個人情報の厳重な管理を行ないます。
%br
%h2 個人情報の利用目的
%h3 本ウェブサイトでは、お客様からのお問い合わせ時に、お名前、e-mailアドレス、電話番号等の個人情報をご登録いただく場合がございますが、これらの個人情報はご提供いただく際の目的以外では利用いたしません。
お客さまからお預かりした個人情報は、当社からのご連絡や業務のご案内やご質問に対する回答として、電子メールや資料のご送付に利用いたします。
%br
%h2 個人情報の第三者への開示・提供の禁止
%h3 当社は、お客さまよりお預かりした個人情報を適切に管理し、次のいずれかに該当する場合を除き、個人情報を第三者に開示いたしません。
%br
%li お客さまの同意がある場合
%li お客さまが希望されるサービスを行なうために当社が業務を委託する業者に対して開示する場合
%li 法令に基づき開示することが必要である場合
%br
%h2 個人情報の安全対策
%h3 当社は、個人情報の正確性及び安全性確保のために、セキュリティに万全の対策を講じています。
%br
%h2 ご本人の照会
%h3 お客さまがご本人の個人情報の照会・修正・削除などをご希望される場合には、ご本人であることを確認の上、対応させていただきます。
%br
%h2 法令、規範の遵守と見直し
%h3 当社は、保有する個人情報に関して適用される日本の法令、その他規範を遵守するとともに、本ポリシーの内容を適宜見直し、その改善に努めます。
%br
%h2 お問い合せ
%h3 当社の個人情報の取扱に関するお問い合せは下記までご連絡ください。
%br
%h4 f.test.jiro@gmail.com

app/views/users/show.html.haml
= render "shared/header-sub"

- breadcrumb :mypage
= render "layouts/breadcrumbs"

.mypage-wrap
  .mypage-wrap-contents
    .left-contents
      .lists-head
        .list-inner
          .list-inner__title
            = link_to "マイページ",user_path(current_user.id)
          .list-inner__title
            = link_to "出品する",new_item_path
          .list-inner__title
            = link_to "出品した商品 出品中",exhibit_users_path
          .list-inner__title
            = link_to "出品した商品 売却済み"
          .list-inner__title
            = link_to "購入した商品 過去の取引"
      .setting
        .setting__title 設定
      .lists-foot
        .list
          .list-inner__title
            - if current_user.card
              = link_to "クレジットカード詳細", card_path(current_user)
            - else
              = link_to "クレジットカード登録", new_card_path
        .list
          .list-inner__title
            - if user_signed_in?
              = link_to "ログアウト", destroy_user_session_path, method: :delete
            - else
              = link_to "ログイン", new_user_session_path, method: :get


    .main-contents
      .user-contents
        .user-inner
          = image_tag asset_path('icon/member_photo_noimage_thumb.png', alt: 'icon', class: 'user-icon')
          .user-name
            = current_user.nickname
          .user-trading-num
            これまでの出品数
          .user-trading-result
            = Item.where(user_id: current_user.id).count

= render "shared/footer-sub"