config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end

  resources :users, only: [:show] do
    collection do
      get 'privacy', to: 'users/privacy'
      get 'exhibit', to: 'users/exhibit'
    end
    get :favorites, on: :collection
  end

  root to:'items#index'
  resources :addresses, only: [:new]

  resources :items do
    collection do
      match 'search', to: 'items#search', via: [:get, :post]
      get 'price_range', defaults: { format: 'json' }
      get 'category_children', defaults: { format: 'json' }
      get 'category_grandchildren', defaults: { format: 'json' }
    end

    resources :purchase do
      collection do
        get 'index', to: 'purchase#index'
        post 'pay', to: 'purchase#pay'
        get 'done', to: 'purchase#done'
      end
    end

    resources :comments, only: [:create, :show, :edit, :destroy]
    collection do
      get 'search'
    end

    resource :favorites, only: [:create, :destroy]
  end

  resources :cards, only: [:new, :show] do
    collection do
      post 'show', to: 'cards#show'
      post 'pay', to: 'cards#pay'
      post 'delete', to: 'cards#delete'
      get 'new', to: 'cards#new'
    end
  end

  resources :categories, only: [:index]

end

app/views/shared/_footer-sub.html.haml
.footer-sub
  .footer-list
    %P
      会社概要（運営会社）
      プライバシーポリシー
      フリマ利用規約
  =link_to root_path do
    = image_tag asset_path('material/logo/logo.png'), alt: 'hurimaのロゴ', class: 'logo-sub'
  .copyright
    FURIMA

app/views/shared/_footer.html.haml
.Third-img
  .Third-img__contents
    .Third-img__contents__title だれでもかんたん、人生を変えるフリマアプリ
    .Third-img__contents__text 今すぐ無料ダウンロード！
    .Third-img__contents__install
      =link_to "#" do
        = image_tag asset_path('App_Store_Badge_US-UK_RGB_blk_092917.svg', alt: 'apple', class: 'Third-img__contents__install__app')
      =link_to "#" do
        = image_tag asset_path('google-play-badge_UK.png', alt: 'google', class: 'Third-img__contents__install__google')
.Fotter
  %ul.Fotter__contents
    .Fotter__contents__content
      %h2.Fotter__contents__content__title FURIMAについて
      %ul
        %li
          = link_to "#" do
            会社概要 （運営会社）
        %li
          = link_to "プライバシーポリシー", privacy_users_path
        %li
          = link_to "#" do
            FURIMA利用規約
        %li
          = link_to "#" do
            ポイントに関する特約
    .Fotter__contents__content
      %h2.Fotter__contents__content__title FURIMAを見る
      %ul
        %li
          =link_to "#" do
            カテゴリー一覧
        %li
          =link_to "#" do
            ブランド一覧
    .Fotter__contents__content
      %h2.Fotter__contents__content__title ヘルプ＆ガイド
      %ul
        %li
          =link_to "#" do
            FURIMAガイド
        %li
          =link_to "#" do
            FURIMAロゴ利用ガイドライン
        %li
          =link_to "#" do
            お知らせ
  .Fotter__logo
    =link_to "#" do
      =image_tag asset_path("material/logo/logo-white.png")
  %p ＠FURIMA

app/views/shared/_fotter.html.haml
.Third-img
  .Third-img__contents
    .Third-img__contents__title だれでもかんたん、人生を変えるフリマアプリ
    .Third-img__contents__text 今すぐ無料ダウンロード！
    .Third-img__contents__install
      =link_to "#" do
        = image_tag asset_path('App_Store_Badge_US-UK_RGB_blk_092917.svg', alt: 'apple', class: 'Third-img__contents__install__app')
      =link_to "#" do
        = image_tag asset_path('google-play-badge_UK.png', alt: 'google', class: 'Third-img__contents__install__google')
.Fotter
  %ul.Fotter__contents
    .Fotter__contents__content
      %h2.Fotter__contents__content__title FURIMAについて
      %ul
        %li
          = link_to "#" do
            会社概要 （運営会社）
        %li
          = link_to "#" do
            プライバシーポリシー
        %li
          = link_to "#" do
            FURIMA利用規約
        %li
          = link_to "#" do
            ポイントに関する特約
    .Fotter__contents__content
      %h2.Fotter__contents__content__title FURIMAを見る
      %ul
        %li
          =link_to "#" do
            カテゴリー一覧
        %li
          =link_to "#" do
            ブランド一覧
    .Fotter__contents__content
      %h2.Fotter__contents__content__title ヘルプ＆ガイド
      %ul
        %li
          =link_to "#" do
            FURIMAガイド
        %li
          =link_to "#" do
            FURIMAロゴ利用ガイドライン
        %li
          =link_to "#" do
            お知らせ
  .Fotter__logo
    =link_to "#" do
      =image_tag asset_path("material/logo/logo-white.png")
  %p ＠FURIMA

app/views/shared/_header-sub.html.haml
.header-sub
  =link_to root_path do
    = image_tag asset_path('material/logo/logo.png'), alt: 'hurimaのロゴ', class: 'logo-sub'

app/views/shared/_header.html.haml
.Header
  .Header__inner
    .Header__inner__main
      %h1.Header__inner__main__logo
        =link_to root_path do
          = image_tag asset_path('material/logo/logo.png')
      .Header__inner__main__search
        -# = form_with(url: search_items_path, method: :get, local: true) do |f|
        -#   = f.text_field :keyword, placeholder: 'キーワードから探す', class: "Header__inner__main__search__input"
        -#   %button{type: "submit"}
        = search_form_for(@q, url: search_items_path, class:"Header__inner__main__search__form") do |f|
          = f.text_field :name_has_every_term, class:"Header__inner__main__search__input", placeholder: "キーワードから探す"
          = button_tag type: "submit" do

            .Header__inner__main__search__icon
              = image_tag asset_path("material/icon/icon-search 1.png")
    .Header__inner__nav
      %ul.Header__inner__nav__left
        %li.Header__inner__nav__left__category
          %ul
            %li
            = link_to "#", class: "category__search search__btn" do
              カテゴリー
            %ul.category__parent.category__list
              - @parents.each do |parent|
                %li
                  = link_to "#", class: "category__parent--name" do
                    = parent.name
                  %ul.category__child.category__list
                    - parent.children.each do |child|
                      %li
                        = link_to "#", class: "category__child--name" do
                          = child.name
                        %ul.category__grandchild.category__list
                          - child.children.each do |grandchild|
                            %li
                              = link_to "#", class: "category__grandchild--name" do
                                = grandchild.name

        %li.Header__inner__nav__left__brand
          = link_to "#", id: "brandBtn" do
            ブランド
      %ul.Header__inner__nav__right
        %li.Header__inner__nav__right__login
          - if user_signed_in?
            = link_to "ログアウト", destroy_user_session_path, method: :delete
          - else
            = link_to "ログイン", new_user_session_path, method: :get
        %li.Header__inner__nav__right__new
          - if user_signed_in?
            = link_to "マイページ", user_path(current_user.id)
          - else
            = link_to "新規会員登録", new_user_registration_path