config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end

  resources :users, only: [:show] do
    collection do
      get 'privacy', to: 'users/privacy'
      get 'exhibit', to: 'users/exhibit'
    end
    get :favorites, on: :collection
  end

  root to:'items#index'
  resources :addresses, only: [:new]

  resources :items do
    collection do
      match 'search', to: 'items#search', via: [:get, :post]
      get 'price_range', defaults: { format: 'json' }
      get 'category_children', defaults: { format: 'json' }
      get 'category_grandchildren', defaults: { format: 'json' }
    end

    resources :purchase do
      collection do
        get 'index', to: 'purchase#index'
        post 'pay', to: 'purchase#pay'
        get 'done', to: 'purchase#done'
      end
    end

    resources :comments, only: [:create, :show, :edit, :destroy]
    collection do
      get 'search'
    end

    resource :favorites, only: [:create, :destroy]
  end

  resources :cards, only: [:new, :show] do
    collection do
      post 'show', to: 'cards#show'
      post 'pay', to: 'cards#pay'
      post 'delete', to: 'cards#delete'
      get 'new', to: 'cards#new'
    end
  end

  resources :categories, only: [:index]

end

app/models/item.rb
class Item < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture
  belongs_to_active_hash :status
  belongs_to_active_hash :delivery_charge
  belongs_to_active_hash :delivery_date
  belongs_to_active_hash :trading_status


  belongs_to :user
  belongs_to :category
  has_many :images, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  accepts_nested_attributes_for :images, allow_destroy: true

  validates :name, presence: true, length: {maximum: 40}
  validates :description, presence: true, length: {maximum: 1000}
  validates :category_id, presence: true
  validates :status_id, presence: true, numericality: { other_than: 0 }
  validates :delivery_charge_id, presence: true, numericality: { other_than: 0 }
  validates :prefecture_id, presence: true, numericality: { other_than: 0 }
  validates :delivery_date_id, presence: true, numericality: { other_tnan: 0 }
  validates :price, presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 300, less_than_or_equal_to: 9999999}

  validates :user_id, presence: true
  validates :trading_status_id, numericality: { greater_than_or_equal_to: 1 }

  def self.search(search)
    return Item.all unless search
    Item.where('name LIKE(?)', "%#{search}%")
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  before_action :set_parents, only: [:index, :new, :create, :show, :search]
  before_action :set_item_search_query


  def index
    @items = Item.all
  end

  def new
    @item = Item.new
    @item.images.new
    @categories = Category.where(ancestry: nil)
  end

  def create
    @item = Item.new(item_params)

    if @item.save!
      params[:item_images][:image].each do |image|
        @item.images.create(image: image, item_id: @item.id)
      end
        redirect_to root_path
    else
      render :new
    end
  end

  def show
    @categories = Category.where(ancestry: nil)
    @user = User.find(@item.user_id)
    @comment = Comment.new
    @commentALL = @item.comments
  end

  def edit
    @categories = Category.where(ancestry: nil)

    grandchild_category = @item.category
    child_category = grandchild_category.parent

    @category_parent_array = Category.where(ancestry: nil).pluck(:name)
    @category_children_array = Category.where(ancestry: child_category.ancestry)
    @category_grandchildren_array = Category.where(ancestry: grandchild_category.ancestry)
  end

  def update
    if @item.update!(item_params)
        if add_item_images = params[:item][:image]
        add_item_images.each do|image|
          @item.images.create(image: image, item_id: @item.id) if @item.images.count <= 10
        end
      end
      redirect_to root_path
    else
    render :edit
    end
  end

  def destroy
    if current_user.id == @item.user_id && @item.destroy
      redirect_to root_path, notice: "削除しました"
    else
      render :show
    end
  end

  def search

    @items = Item.search(params[:keyword]).limit(40).order("created_at DESC")
    @keyword = params[:keyword]

    @search_parents = Category.where(ancestry: nil).pluck(:name)
    @keyword = params.require(:q)[:name_has_every_term]

    if params[:q].present?
    # 検索フォームからアクセスした時の処理
      @search = Item.ransack(search_params)
      @items = @search.result
    else
    # 検索フォーム以外からアクセスした時の処理
      params[:q] = { sorts: 'id desc' }
      @search = Item.ransack()
      @items = Item.all
    end

    @pages = Kaminari.paginate_array(@items).page(params[:page]).per(5)

  end

  #ajax通信でデータ取得のためのメソッド
  def price_range
    if params[:price_id].nil?
      @price_range = PriceRange.find(params[:min], params[:max])
    else
      @price_range = PriceRange.find(params[:price_id])
    end
  end

  #親カテゴリが選択された後に動くアクション
  def category_children
    #選択された親カテゴリに紐づく子供カテゴリの配列を取得
    @children = Category.find_by(name: "#{params[:parent_name]}", ancestry: nil).children
  end

  def category_grandchildren
    #選択された子供カテゴリに紐づく子供カテゴリの配列を取得
    @grandchildren = Category.find("#{params[:child_id]}").children

  end

  private

  def item_params
    params.require(:item)
          .permit(:name,
                  :description,
                  :brand,
                  :category_id,
                  :status_id,
                  :delivery_charge_id,
                  :prefecture_id,
                  :delivery_date_id,
                  :price,
                  :brand,
                  images_attributes:
                  [:image, :_destroy, :id]).merge(user_id: current_user.id, trading_status_id: 1)
  end

  def set_item
    @item = Item.find_by_id(params[:id])
  end

  def set_parents
    @parents = Category.where(ancestry: nil)
  end

  def search_params
    params.require(:q).permit(
      :sorts,
      :name_has_every_term, #config/initializers/ransack.rb
      :category_id,
      :brand_cont,
      :price_gteq,
      :price_lteq,
      category_id_in: [],
      status_id_in: [],
      delivery_charge_id_in: [],
      trading_status_id_in: []
    )
  end

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.haml
.products_new-header
.products_new-main
  .products_new-main__form
    .products_new-main__f--product_new
      = form_with model: @item, local: true, id: "new_product" do |f|
        .products_new-postimage
          .products_new-product__headline
            .products_new-product__headline--title 出品画像
            .products_new-product__headline--required 必須
          %p.products_new-product__explanation 画像をアップロードしてください

          #image-box-1
            - if @item.persisted? && @item.images.count > 0
              - @item.images.each_with_index do |image, i|
                %div{class: "item-image", data:{ image: image.image.filename, index: i}}
                  .item-image__content
                    .item-image__content--icon
                      = image_tag image.image.url, data: { index: i }, width: "114", height: '80'
                  .item-image__operation
                    .item-image__operation--delete 削除
              = f.fields_for :images do |i|
                = i.file_field :image, type: 'file', class: "img-file", name: "item[image][]", value:"", style: "display:none", multiple: :true
                = i.check_box :_destroy, data: {index: i.index}, class: 'hidden-destroy'
              %div{class: "item-num-#{@item.images.count} drag-area", id: "image-box__container"}
                %div{class: "input-area", tabindex: 0}
                  = file_field_tag :image, name: "item[image][]", class: "img-file", value:"", style: "display:none", multiple: :true
                  %label{for: "image", class: "input-area__label"}
                    %i.fas.fa-camera
            - else
              .item-num-0#image-box__container
                = f.fields_for :item_images do |image|
                  %div{class: "input-area", tabindex: 0}
                    = image.file_field :image, type: 'file', class: "img-file", name: "item_images[image][]", value:"", style: "display:none", required: "required", multiple: :true
                    %label{for: "item_item_images_image", class: "input-area__label"}
                      %i.fas.fa-camera
          #required_error_image

        .products_new-title
          .products_new-product__headline
            .products_new-product__headline--title 商品名
            .products_new-product__headline--required 必須
          = f.text_field :name, class:"products_new-title--box", placeholder:"40字まで", maxlength:'40',required: :true
          #required_error_name

        .products_new-product__detaile
          .products_new-product__headline
            .products_new-product__headline--title 商品の説明
            .products_new-product__headline--required 必須
          = f.text_area :description, class:"products_new-product__detaile--box", placeholder:"商品の説明(必須 1000文字以内)", maxlength:'1000',required: :true
          #required_error_description

        .products_new-product_explanation
          .products_new-product_explanation__headline2 商品の詳細
          .products_new-product_explanation__category
            .products_new-product__headline
              .products_new-product__headline--title カテゴリー
              .products_new-product__headline--required 必須
            .products_new-product_explanation__category--box
              = f.collection_select :category_id, @categories, :id, :name, { include_blank: "選択してください", selected:"" }, id: "category_form"
              #required_error_category_id

          .products_new-product_explanation__brand
            .products_new-product__headline
              .products_new-product__headline--title ブランド
              #products_new-product__headline--required 任意
            = f.text_field :brand, class:"products_new-title--box", placeholder:"例)シャネル", maxlength:'40'

          .products_new-product_explanation__condition
            .products_new-product__headline
              .products_new-product__headline--title 商品の状態
              .products_new-product__headline--required 必須
            = f.collection_select(:status_id, Status.all, :id, :name, prompt: "選択してください", required: :true, class: "products_new-product_explanation__condition--box")
            #required_error_status

        .products_new-product_delivery
          .products_new-product_delivery__headline2 配送について
          .products_new-product_delivery__fee
            .products_new-product__headline
              .products_new-product__headline--title 配送料の負担
              .products_new-product__headline--required 必須
            = f.collection_select(:delivery_charge_id, DeliveryCharge.all, :id, :name, prompt: "選択してください", required: :true, class: "products_new-product_delivery__fee--box")
            #required_error_delivery_charge

          .products_new-product_delivery__shipping_area
            .products_new-product__headline
              .products_new-product__headline--title 発送元の地域
              .products_new-product__headline--required 必須
            = f.collection_select(:prefecture_id, Prefecture.all, :id, :name, prompt: "選択してください", required: :true)
            #required_error_prefecture_id

          .products_new-product_delivery__shipping_days
            .products_new-product__headline
              .products_new-product__headline--title 発送までの日数
              .products_new-product__headline--required 必須
            = f.collection_select(:delivery_date_id, DeliveryDate.all, :id, :name, prompt: "選択してください", required: :true, class: "products_new-product_delivery__shipping_days--box")
            #required_error_delivery_date

          .products_new-product_price
            .products_new-product_price__headline2 価格（¥300〜9,999,999）
            .products_new-product_price--displayflex
              .products_new-product__headline
                .products_new-product__headline--title 販売価格
                .products_new-product__headline--required 必須
              .products_new-product_price--select
                %p.products_new-product_price--yen ¥
                = f.number_field :price, required: :true, class: "products_new-product_price--box", placeholder:"0"
                #required_error_price

        .products_new-product__submit
          = f.submit '出品する', class: "item-form-btn"

app/views/items/_fotter.html.haml
.Fotter
  %ul.Fotter__contents
    .Fotter__contents__content
      %h2.Fotter__contents__content__title FURIMAについて
      %ul
        %li
          = link_to "#" do
            会社概要 （運営会社）
        %li
          = link_to "#" do
            プライバシーポリシー
        %li
          = link_to "#" do
            FURIMA利用規約
        %li
          = link_to "#" do
            ポイントに関する特約
    .Fotter__contents__content
      %h2.Fotter__contents__content__title FURIMAを見る
      %ul
        %li
          =link_to "#" do
            カテゴリー一覧
        %li
          =link_to "#" do
            ブランド一覧
    .Fotter__contents__content
      %h2.Fotter__contents__content__title ヘルプ＆ガイド
      %ul
        %li
          =link_to "#" do
            FURIMAガイド
        %li
          =link_to "#" do
            FURIMAロゴ利用ガイドライン
        %li
          =link_to "#" do
            お知らせ
  .Fotter__logo
    =link_to "#" do
      =image_tag asset_path("material/logo/logo-white.png")
  %p ＠FURIMA

app/views/items/_main.html.haml
.First-img
  .First-img__contents
    .First-img__contents__title 人生を変えるフリマアプリ
    .First-img__contents__text
      %p FURIMAはだれでも簡単に出品・購入できる
      %p フリマアプリです
    .First-img__contents__install
      = image_tag asset_path('App_Store_Badge_US-UK_RGB_blk_092917.svg', alt: 'apple', class: 'First-img__contents__install__app')
      = image_tag asset_path('google-play-badge_UK.png', alt: 'google', class: 'First-img__contents__install__google')

.Reason
  .Reason__title FURIMAが選ばれる３つの理由
  .Reason__lists
    .Reason__lists__list
      .Reason__lists__list__picture
        = image_tag asset_path('material/pict/pict-reason-01.jpg', alt: '画像１', class: 'Reason__lists__list__picture__img')
        .Reason__lists__list__picture__num 1
      .Reason__lists__list__text
        %span 3分
        ですぐに出品
      .Reason__lists__list__description スマホで入力するだけで簡単に出品できる！
    .Reason__lists__list
      .Reason__lists__list__picture
        = image_tag asset_path('material/pict/pict-reason-02.jpg', alt: '画像２', class: 'Reason__lists__list__picture__img')
        .Reason__lists__list__picture__num 2
      .Reason__lists__list__text
        %span シンプル
        で使いやすい
      .Reason__lists__list__description めんどくさい入力は必要なく、検索も購入もスムーズ！
    .Reason__lists__list
      .Reason__lists__list__picture
        = image_tag asset_path('material/pict/pict-reason-03.jpg', alt: '画像３', class: 'Reason__lists__list__picture__img')
        .Reason__lists__list__picture__num 3
      .Reason__lists__list__text
        手数料
        %span 業界最安
      .Reason__lists__list__description 最大３％でお得に出品＆購入！



.Second-img
  .Second-img__contents
    .Second-img__contents__title 会員数日本一位
    .Second-img__contents__text
      %p FURIMAは、フリマアプリで最も人気。
      %p 出品・購入回数も業界最多です！
      %p ほしかったあの商品に出会えるかもしれません。
    .Second-img__contents__install
      =link_to "#" do
        = image_tag asset_path('App_Store_Badge_US-UK_RGB_blk_092917.svg', alt: 'apple', class: 'Second-img__contents__install__app')
      =link_to "#" do
        = image_tag asset_path('google-play-badge_UK.png', alt: 'google', class: 'Second-img__contents__install__google')

.Feature
  .Feature__title FURIMAの特徴
  .Feature__lists
    .Feature__lists__list
      .Feature__lists__list__picture
        = image_tag asset_path('material/icon/icon-01.png')
      .Feature__lists__list__text 簡単に売り買いできる
      .Feature__lists__list__descriptin スマホひとつで、いつでもどこでも簡単に出品・購入が可能！
    .Feature__lists__list
      .Feature__lists__list__picture
        = image_tag asset_path('material/icon/icon-03.png')
      .Feature__lists__list__text 売上金は即日振込みに対応
      .Feature__lists__list__descriptin 午前9時までに振込を依頼いただければ、翌日に指定の口座に入金いたします！
    .Feature__lists__list
      .Feature__lists__list__picture
        = image_tag asset_path('material/icon/icon-04.png')
      .Feature__lists__list__text 様々な支払いに対応
      .Feature__lists__list__descriptin お支払いは、クレジットカードだけでなく、ポイントや売上金など多彩な方法があります。

.Pickup-category
  %h2.Pickup-category__title ピックアップカテゴリー
  .Pickup-category__product
    .Pickup-category__product__subtitle
      = link_to "#" do
        %h3.Pickup-category__product__subtitle__name 新規投稿商品
    .Pickup-category__product__lists
      - @items.each do |item|
        = link_to item_path(item.id) do
          .Pickup-category__product__lists__list
            .Pickup-category__product__lists__list__picture
              = image_tag item.images.first.image.url, size:'220*150'
            .Pickup-category__product__lists__list__body
              .Pickup-category__product__lists__list__body__name
                = item.name
              .Pickup-category__product__lists__list__body__details
                %ul
                  %li= "#{item.price}円"
                  %li
                    =icon('fa','star')
                    4
                %p（税込）
                - if item.trading_status_id == 2
                  .item-sold-out-box
                    .item-sold-out-box__inner
                      SOLD

.Pickup-brand
  %h2.Pickup-brand__title ピックアップブランド
  .Pickup-brand__product
    .Pickup-brand__product__subtitle
      =link_to "#" do
        %h3.Pickup-brand__product__subtitle__name アーカイバ
    .Pickup-brand__product__lists
      - @items.each do |item|
        = link_to item_path(item.id) do
          .Pickup-brand__product__lists__list
            .Pickup-brand__product__lists__list__picture
              = image_tag item.images.first.image.url, size:'220*150'
            .Pickup-brand__product__lists__list__body
              .Pickup-brand__product__lists__list__body__name
                = item.name
              .Pickup-brand__product__lists__list__body__details
                %ul
                  %li= "#{item.price}円"
                  %li
                    =icon('fa','star')
                    1
                %p （税込）
                - if item.trading_status_id == 2
                  .item-sold-out-box
                    .item-sold-out-box__inner
                      SOLD

app/views/items/index.html.haml
.wrapper
  = render "shared/header"
  = render "main"
  = render "shared/footer"
  = link_to new_item_path do
    .item-icon-wrap
      .item-icon-wrap__inner
        .item-icon-wrap__inner--text
          出品する
        = icon('fas', 'camera', class:'item-icon')

app/views/items/new.html.haml
= render "shared/header-sub"
= render partial: 'form'
= render "shared/footer-sub"

app/views/items/search.html.haml
= render "shared/header"


-# .search_main
-#   .search_main__content
-#     %h3.search_main__content__ttl
-#       = "#{@keyword}の検索結果"
-#     %ul.search_main__content__ul
-#       - @items.each do |item|
-#         %li
-#           = link_to item_path(item), class: 'search_main__content__item' do
-#             = image_tag "#{item.images[0].image}", class: 'search_main__content__item__image'
-#             %p.search_main__content__item__name
-#               = item.name
-#             %p.search_main__content__item__price
-#               = "¥#{item.price}"


.search-index-wrap
  .search-index-inner
    .search-index-inner__left
      .all-warp
        .l-search-wrap
          = search_form_for @q, url: search_items_path, id: "item_search_form", html: { method: :post } do |f|
            .sort-menu
              = f.select( :sorts, { '並び替え': 'id desc', '価格の安い順': 'price asc', '価格の高い順': 'price desc', '出品の古い順': 'updated_at asc', '出品の新しい順': 'updated_at desc' } , { selected: params[:q][:sorts] }, { onchange: 'this.form.submit()'} )
            .detail-search-wrap
              .head-text
                詳細検索
                .search-form-keyword
                  = icon("fas", "plus", class: "icon-plus")
                  = f.label :name_has_every_term, "キーワードを追加する（検索する）"
                  = f.text_field :name_has_every_term, placeholder: "例）値下げ", class: "input-default-search"

              .search-form-category
                = icon("fas", "list", class: "icon-list")
                = f.label :category_id, "カテゴリを選択する"
                = icon("fas", "angle-down", class: "icon-down-category")
                .items-search-category-form
                  = f.select :category_id, options_for_select(@search_parents), {include_blank: "選択してください"}, {id: "parent_category_search"}

              .search-form-extend-brand
                = icon("fas", "tag", class: "icon-tag")
                = f.label :brand_cont, "ブランド名から探す"
                = f.text_field :brand_cont, placeholder: "例）シャネル", class: "input-default-search"

              .search-form-price
                = icon("fas", "coins", class: "icon-coins")
                = f.label :price, '価格'
                = icon("fas", "angle-down", class: "icon-down")
                = select_tag :price_range, options_from_collection_for_select(PriceRange.all, :id, :name), { prompt: "選択してください" }
                = f.number_field :price_gteq, placeholder: "¥ Min", class: "price-range__input"
                〜
                = f.number_field :price_lteq, placeholder: "¥ Max", class: "price-range__input"

              .search-form-status
                = icon("fas", "star", class: "icon-star")
                = f.label :status_id, "商品の状態"
                .status-checkbox-all-wrap
                  .status-checkbox-all__btn
                    %input{type: 'checkbox', id: "status_all", class: "js-checkbox-all"}
                    .status-checkbox-all__label
                      = label_tag :status_all, "すべて"
                  = f.collection_check_boxes :status_id_in, Status.all, :id, :name, include_hidden: false do |s|
                    .status-check-box
                      .status-checkbox-each-box.js_search_checkbox
                        = s.check_box
                      .status-checbox-each-title
                        = s.label {s.text}

              .search-form-delivery-charge
                = icon("fas", "truck", class: "icon-truck")
                = f.label :derivery_charge_id, "配送料の負担"
                .delivery-charge-checkbox-all-wrap
                  .delivery-charge-checkbox-all__btn
                    %input{type: 'checkbox', id:  "delivery_charge_all", class: "js-checkbox-all"}
                    .delivery-charege-all__label
                      = label_tag :delivery_charge_all, "すべて"
                  = f.collection_check_boxes :delivery_charge_id_in, DeliveryCharge.all, :id, :name,include_hidden: false do |d|
                    .delivery-charege-check-box
                      .delivery-charge-checkbox-each-box.js_search_checkbox
                        = d.check_box
                      .delivery-charege-checbox-each-title
                        = d.label {d.text}

              .search-form-trading-status
                = icon("fas", "shopping-cart", class: "icon-cart")
                = f.label :trading_status_id,  "販売状況"
                .trading-status-checkbox-all-wrap
                  .trading-status-checkbox-all__btn
                    %input{type: 'checkbox', id:  "trading_status_all", class: "js-checkbox-all"}
                    .trading-status-all__label
                      = label_tag :trading_status_all, "すべて"
                  = f.collection_check_boxes :trading_status_id_in, TradingStatus.all, :id, :name,include_hidden: false do |t|
                    .tradig-status-check-box
                      .trading-status-checkbox-each-box.js_search_checkbox
                        = t.check_box
                      .trading-status-checbox-each-title
                        = t.label {t.text}

              .btn-wrap
                .btn-inner
                  .btn-clear
                    .btn-text
                      = f.submit "クリア", class: "btn-text-clear", id: "js_search_clear"
                  .btn-complete
                    .btn-text
                      = f.submit "完了", class: "btn-text-complete"

    .search-index-inner__right
      .search-result-wrap
        .search-result-container
          .search-result-header
            - if @keyword.present?
              = "「#{@keyword}」の検索結果"
            - else
              検索結果
          .search-result-number
            = "#{@pages.total_count}件"
          .search-result-items
            .search-result-items-inner
              .serach-result-items-row
                .Pickup-category__product__lists
                  - @items.each do |item|
                    = link_to item_path(item.id) do
                      .Pickup-category__product__lists__list
                        .Pickup-category__product__lists__list__picture
                          = image_tag item.images.first.image.url, size:'220*150'
                        .Pickup-category__product__lists__list__body
                          .Pickup-category__product__lists__list__body__name
                            = item.name
                          .Pickup-category__product__lists__list__body__details
                            %ul
                              %li= "#{item.price}円"
                              %li
                                =icon('fa','star')
                                4
                            %p（税込）
                            - if item.trading_status == 2
                              .item-sold-out-box
                                .item-sold-out-box__inner
                                  SOLD
      = paginate @pages

= render "shared/footer"

app/views/items/show.html.haml
= render "shared/header-sub"
.show-main
  .show-wrapper
    .show-contents
      .show-contents__topContent
        .show-itemBox
          %h2.show-itemBox__name
            = @item.name
          .show-itemBox__photo
            %ul
              %li
                = image_tag @item.images.first.image.url, alt: '出品写真', height: '346px', width: '80%'
                - if @item.trading_status_id == 2
                  .item-sold-out-box-show
                    .item-sold-out-box-show__inner
                      SOLD
          .show-itemBox__photo__inner-photo
            .show-itemBox__photo__inner-photo__under-photo
              -# = image_tag @item.images.first.image.url, alt: '出品写真', height: '80px', width: '80%', class: 'image-sub'
              - @item.images.each_with_index do |image, i|
                = image_tag image.image.url
          .show-itemBox__price
            %span
              = "¥#{@item.price}"
            .show-itemBox__price__tax
              %span
                (税込)
              %span
                送料込み
          - if @item.trading_status_id == 1
            - if user_signed_in?
              - if current_user.id == @item.user_id
                = link_to "商品を削除する", item_path(@item), method: :delete, class:"snow-itemBox__buyscreen"
                = link_to "商品を編集する", edit_item_path(@item.id), method: :get, class:"snow-itemBox__buyscreen"
              - elsif current_user.id != @item.user_id
                = link_to "購入確認画面に進む", "/items/#{@item.id}/purchase", method: :get, class:"snow-itemBox__buyscreen"
          - else
            .item-sold-out
              売り切れました
          .show-itemBox__description
            = @item.description
          .show-itemBox__table
            %table
              %tbody
                %tr
                  %th 出品者
                  %td
                    = @user.nickname
                %tr
                  %th カテゴリー
                  %td
                    - @categories.each do |parent|
                      - parent.children.each do |child|
                        - child.children.each do |grandchild|
                          -if @item.category_id == grandchild.id
                            = link_to '#' do
                              = parent.name
                            %br
                            = link_to '#' do
                              = child.name
                            %br
                            =link_to '#' do
                              = grandchild.name
                            %br
                %tr
                  %th ブランド
                  %td
                    = link_to "#{@item.brand}", "#"
                %tr
                  %th 商品の状態
                  %td
                    = @item.status.name
                %tr
                  %th 配送料の負担
                  %td
                    = @item.delivery_charge.name
                %tr
                  %th 配送元の地域
                  %td
                    = link_to "#{@item.prefecture.name}", "#"
                %tr
                  %th 発送日の目安
                  %td
                    = @item.delivery_date.name

          .optionalArea
            %ul
              %li.optionalBtnlikebtn
                = render "favorites/favorite"
            %ul.optional
              %li.optionalBtn
                不適切な商品の通報
  -if user_signed_in?
    = render "comments/comment"
= render "shared/footer-sub"