config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end

  resources :users, only: [:show] do
    collection do
      get 'privacy', to: 'users/privacy'
      get 'exhibit', to: 'users/exhibit'
    end
    get :favorites, on: :collection
  end

  root to:'items#index'
  resources :addresses, only: [:new]

  resources :items do
    collection do
      match 'search', to: 'items#search', via: [:get, :post]
      get 'price_range', defaults: { format: 'json' }
      get 'category_children', defaults: { format: 'json' }
      get 'category_grandchildren', defaults: { format: 'json' }
    end

    resources :purchase do
      collection do
        get 'index', to: 'purchase#index'
        post 'pay', to: 'purchase#pay'
        get 'done', to: 'purchase#done'
      end
    end

    resources :comments, only: [:create, :show, :edit, :destroy]
    collection do
      get 'search'
    end

    resource :favorites, only: [:create, :destroy]
  end

  resources :cards, only: [:new, :show] do
    collection do
      post 'show', to: 'cards#show'
      post 'pay', to: 'cards#pay'
      post 'delete', to: 'cards#delete'
      get 'new', to: 'cards#new'
    end
  end

  resources :categories, only: [:index]

end

app/models/card.rb
class Card < ApplicationRecord
  validates :user_id, :customer_id,  presence: true

  belongs_to :user
  # pay.jpのためにview側でid付与のために、アクティブハッシュをコメントアウト

  # extend ActiveHash::Associations::ActiveRecordExtensions
  # belongs_to_active_hash :birth_year
  # belongs_to_active_hash :card_validity_year

  # validates :birth_year, :card_validity_year, presence: true
  # validates :birth_year_id, numericality: { other_than: 0}
  # validates :card_validity_year_id, numericality: { other_than: 0}

  belongs_to :user

  validates :user_id, :customer_id, :card_id, presence: true
  validates :user_id, uniqueness: true
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController

  require "payjp"
  before_action :set_card, only: [:delete, :show]

  def new
    card = Card.where(user_id: current_user.id)
    redirect_to action: "show" if card.exists?
  end

  def pay #payjpとCardのデータベース作成を実施
    Payjp.api_key = Rails.application.credentials.dig(:payjp, :PAYJP_PRIVATE_KEY)
    if params['token'].blank?
      redirect_to action: "new"
    else
      customer = Payjp::Customer.create(
      # description: '登録テスト',
      # email: current_user.email,
      card: params['token'],
      metadata: {user_id: current_user.id}
      ) #念の為metadataにuser_idを入れました
      @card = Card.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      if @card.save
        redirect_to action: "show"
      else
        redirect_to action: "pay"
      end
    end
  end

  def delete #PayjpとCardデータベースを削除
    if @card.present?
      Payjp.api_key = Rails.application.credentials.dig(:payjp, :PAYJP_PRIVATE_KEY)
      customer = Payjp::Customer.retrieve(@card.customer_id)
      customer.delete
      @card.delete
    end
      flash[:alert] = "登録カード情報を削除しました"
      redirect_to action: "new"
  end

  def show #Cardのデータpayjpに送り情報を取り出す
    if @card.blank?
      redirect_to action: "new"
    else
      Payjp.api_key = Rails.application.credentials.dig(:payjp, :PAYJP_PRIVATE_KEY)
      customer = Payjp::Customer.retrieve(@card.customer_id)
      @default_card_information = customer.cards.retrieve(@card.card_id)

      @card_brand = @default_card_information.brand
      case @card_brand
      when "Visa"
        @card_image = "visa.png"
      when "JCB"
        @card_image = "jcb.png"
      when "MasterCard"
        @card_image = "mastercard.png"
      when "American Express"
        @card_image = "americanExpress.png"
      when "Diners Club"
        @card_image = "diners.png"
      end
    end
  end

  private

  def set_card
    @card = Card.where(user_id: current_user.id).first
  end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/new.html.haml
= render "shared/header-sub"
.card-wrap
  .card-main
    .card-inner
      .card-inner__head
        .card-inner__head--text
          クレジットカード情報入力
      .card-inner-wrap
        = form_with url: pay_cards_path, method: :post, id: 'charge-form',html:{name: "inputForm"} do |f|
          .card-inner-wrap__number-wrap
            .card-inner-wrap__number-wrap--text
              カード番号
            .card-inner-wrap__number-wrap--form-required
              必須
          = f.text_field :card_number, placeholder: "半角英数字のみ", class: "card-inner-wrap__number--textfield", maxlength: "16"
          .card-inner-wrap__img
            = image_tag asset_path('cards_icon/visa.png', alt: 'icon', class: 'card-inner-wrap__img--cards')
            = image_tag asset_path('cards_icon/jcb.png', alt: 'icon', class: 'card-inner-wrap__img--cards')
            = image_tag asset_path('cards_icon/mastercard.png', alt: 'icon', class: 'card-inner-wrap__img--cards')
            = image_tag asset_path('cards_icon/diners.png', alt: 'icon', class: 'card-inner-wrap__img--cards')
            = image_tag asset_path('cards_icon/americanExpress.png', alt: 'icon', class: 'card-inner-wrap__img--cards')
          .card-inner-wrap__validity-date
            .card-inner-wrap__validity-date--text
              有効期限
            .card-inner-wrap__validity-date--form-required
              必須
          .card-inner-wrap-input
            // 新たなid付与のためにselect,optionに変更
            -# = f.collection_select(:birth_month_id, BirthMonth.all, :id, :name,{class:"card-inner-wrap-input__select-month"})
            = f.select :exp_month, [["--",0],["01",1],["02",2],["03",3],["04",4],["05",5],["06",6],["07",7],["08",8],["09",9],["10",10],["11",11],["12",12]],{} , class: 'card-inner-wrap-input__select-month'
            .card-inner-wrap-input__text-month
              月
            // 新たなid付与のためにselect,optionに変更
            -# = f.collection_select(:card_validity_year_id, CardValidityYear.all, :id, :name, {class:"card-inner-wrap-input__select-year"})
            = f.select :exp_year, [["--",0],["20",2020],["21",2021],["22",2022],["23",2023],["24",2024],["25",2025],["26",2026],["27",2027],["28",2028],["29",2029]],{} , class: 'card-inner-wrap-input__select-year'
            .card-inner-wrap-input__text-year
              年
          .card-inner-wrap-security
            .card-inner-wrap-security__text
              セキュリティコード
            .card-inner-wrap-security__form-required
              必須
          .card-inner-wrap-security-input-number
            = f.text_field :cvc, placeholder: "カード背面3桁または4桁の番号", class: "card-inner-wrap-security-input-number__input", maxlength: "4"
          #card_token
            = f.submit "登録する", class: "submit", id: "token_submit"

= render "shared/footer-sub"

app/views/cards/show.html.haml
= render "shared/header-sub"
- breadcrumb :card_show
= render "layouts/breadcrumbs"
.mypage-wrap
  .mypage-wrap-contents
    .left-contents
      .lists-head
        .list-inner
          .list-inner__title
            = link_to "マイページ",user_path(current_user.id)
          .list-inner__title
            = link_to "出品する",new_item_path
            -# root_path 仮置き
          .list-inner__title
            = link_to "出品した商品 出品中",root_path
          .list-inner__title
            = link_to "出品した商品 売却済み",root_path
          .list-inner__title
            = link_to "購入した商品 過去の取引",root_path
      .setting
        .setting__title 設定
      .lists-foot
        .list
          .list-inner__title
            - if current_user.card
              = link_to "クレジットカード詳細", card_path(current_user)
            - else
              = link_to "クレジットカード登録", new_card_path
        .list
          .list-inner__title
            - if user_signed_in?
              = link_to "ログアウト", destroy_user_session_path, method: :delete
            - else
              = link_to "ログイン", new_user_session_path, method: :get

    .card-detail-warp
      .card-detail-inner
        .card-detail-header
          登録クレジットカード情報
        .card-detail-inner-wrap
          .card-detail-contents
            .card-detail-contents-inner
              .card-detail-contents-inner__content
                = "**** **** **** " + @default_card_information.last4
              .card-detail-contents-inner__exp
                有効期限
                - exp_month = @default_card_information.exp_month.to_s
                - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
                = exp_month + " / " + exp_year
              = image_tag asset_path("cards_icon/#{@card_image}")
              .card-detail-contents-inner__delete-btn
                = form_with(url:delete_cards_path, method: :post, id: 'charge-form',  name: "inputForm") do |f|
                  %input{ type: "hidden", name: "card_id", value: "" }
                  = f.submit "削除する",{class:"card-delete-btn"}


= render "shared/footer-sub"